name: notebook-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pip
  - pip:
    - ipywidgets
    - ipython
    - numpy
    - pandas
    - matplotlib
    - plotly
    - seaborn
    - sklearn